# Generated by Django 2.1.7 on 2019-03-14 02:37

import ckeditor.fields
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('slug', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1024)),
                ('short_desc', models.TextField()),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/news-body/')),
                ('body', ckeditor.fields.RichTextField()),
                ('category', models.ManyToManyField(to='News.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='NewsBodyImage',
        ),
    ]
