# Generated by Django 2.1.7 on 2019-03-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0002_auto_20190314_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='body',
        ),
    ]
