# Generated by Django 2.1.7 on 2019-03-14 02:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0003_remove_news_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=''),
        ),
    ]
