# Generated by Django 2.1.7 on 2019-03-14 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0004_news_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 19, 51, 34, 742779)),
        ),
    ]
