# Generated by Django 2.1.7 on 2019-03-14 09:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0008_remove_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 14, 9, 58, 45, 336971, tzinfo=utc)),
        ),
    ]
