# Generated by Django 2.1.7 on 2019-03-15 03:01

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0011_news_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категирия', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=2028),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to='images/news-posters/'),
        ),
    ]
