# Generated by Django 2.1.7 on 2019-03-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_auto_20190315_1301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='tags',
        ),
    ]
