# Generated by Django 2.1.7 on 2019-03-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0013_remove_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='tags',
            field=models.TextField(blank=True, default=''),
        ),
    ]
