# Generated by Django 2.1.7 on 2019-03-16 13:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0015_auto_20190315_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date'], 'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='news',
            name='date_edit',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(default='', verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ManyToManyField(to='News.Category', verbose_name='Категории'),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(help_text='Соотношение сторон будет преобразовано в 2:1', upload_to='images/news-posters/', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_desc',
            field=models.TextField(verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='news',
            name='tags',
            field=models.TextField(blank=True, default='', verbose_name='Тэги (через запятую)'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1024, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='news',
            name='visible',
            field=models.BooleanField(default=False, verbose_name='Показывать новость'),
        ),
    ]
